akka/akka-paradox

- .travis.yml
- build.sbt
- project/Publish.scala
- project/plugins.sbt
- version.sbt
> Add .travis.yml for building

- README.md
- project/Publish.scala
> bintrayRelease (#7)

- theme/src/main/assets/js/groups.js
- theme/src/main/assets/js/page.js
Making our theme more consistent with upstream again.
When this is merged we can publish akka documentation as one tree (https://github.com/akka/akka/pull/23544).
For akka-http we're still in the process of merging markdown and blocked on some paradox features (see https://github.com/akka/akka-http/issues/1290)
> Remove page refresh logic, add query parameter for selecting groups

- project/Dependencies.scala
> Update paradox dependency

- theme/src/main/assets/search.st
As the language switch is now handled completely at the client side
> Remove 'language' facet from the algolia parameters

- .travis.yml
- build.sbt
- project/build.properties
- project/plugins.sbt
Avoiding the double-upload-problem in https://travis-ci.org/akka/akka-paradox/builds/327153903
> Sbt 1.0 all the way

- build.sbt
- project/plugins.sbt
To more easily spot differences between builds
> Strip timestamps etc from deliverables

- theme/src/main/assets/page.st
- theme/src/main/assets/projectSpecificFooter.st
Prerequisite to fixing akka/akka#25244
> Template to hook in custom stuff per project

- theme/src/main/assets/js/groups.js
Tested locally, seems :+1: 
https://github.com/lightbend/paradox/issues/220
> Escape cookie value

- .gitignore
- project/Dependencies.scala
> Upgrade paradox to fix sample truncation

- build.sbt
- theme/src/main/assets/css/page.css
> Goto source link icon

- .travis.yml
> Get JDK via jabba

- README.md
- build.sbt
- plugin/src/sbt-test/sbt-paradox-akka/simple/build.sbt
- plugin/src/sbt-test/sbt-paradox-akka/simple/project/plugins.sbt
- plugin/src/sbt-test/sbt-paradox-akka/simple/src/main/paradox/index.md
- plugin/src/sbt-test/sbt-paradox-akka/simple/src/main/paradox/page1.md
- plugin/src/sbt-test/sbt-paradox-akka/simple/src/main/paradox/page2.md
- plugin/src/sbt-test/sbt-paradox-akka/simple/test
refs #29
@rasummer would this be helpful to you?
> Scripted test for local testing

- build.sbt
- plugin/src/sbt-test/sbt-paradox-akka/simple/build.sbt
- theme/src/main/assets/page.st
Requires https://github.com/lightbend/paradox/pull/343
> Show license footer only when appropriate

- theme/src/main/assets/page.st
This makes it possible to make search engines ignore certain pages.
> Make meta robots setable

- plugin/src/sbt-test/sbt-paradox-akka/simple/project/project-info.conf
- plugin/src/sbt-test/sbt-paradox-akka/simple/src/main/paradox/page1.md
- theme/src/main/assets/css/page-6.css
- theme/src/main/assets/js/metadata-toggle.js
- theme/src/main/assets/page.st
Also some styling to the table when visible
Preview:
Initial:
After toggle:
> Hide project info by default

- build.sbt
https://github.com/lightbend/sbt-paradox-apidoc/releases/tag/v0.9
> Apidoc 0.9

- build.sbt
- project/plugins.sbt
Bring https://github.com/lightbend/paradox/issues/426 in.
> Paradox 0.8.0

- build.sbt
- project/plugins.sbt
- theme/src/main/assets/css/page-8.css
- theme/src/main/assets/js/snippets.js
- theme/src/main/assets/page.st
Upgrade to paradox 0.9.2 for and some theme updates for the buttons
> copy button 

- .travis.yml
> Use latest jabba install script

- build.sbt
- project/build.properties
> Update sbt to 1.5.5

- theme/src/main/assets/lbHeader.st
Update banner to link to Kalix.
> Kalix banner

- theme/src/main/assets/js/lbHeader.js
- theme/src/main/assets/lbHeader.st
@ennru 
Updated Lightbend banner for the Akka Paradox theme.
> Add new Lightbend Banner

- theme/src/main/assets/copyright.st
https://www.lightbend.com/blog/why-we-are-changing-the-license-for-akka
> Show BSL in footer, depending on the project config

- build.sbt
- project/plugins.sbt
References
- https://github.com/lightbend/paradox/releases/tag/v0.10.4
> bump: paradox 0.10.4 (repository directive)

- build.sbt
- project/plugins.sbt
References
- https://github.com/lightbend/paradox/releases/tag/v0.10.5
> bump: paradox 0.10.5 (repository directive fix)

- build.sbt
- project/plugins.sbt
@johanandren Same game again, can you merge if green and cut `v0.54` afterwards?
> sbt-paradox 0.10.6

- build.sbt
References
- https://github.com/lightbend/sbt-paradox-lightbend-project-info/pull/8
> bump: lightbend-project-info 3.0.0

- build.sbt
References
- https://github.com/lightbend/sbt-paradox-apidoc/releases/tag/v1.1.0
- https://github.com/lightbend/sbt-paradox-lightbend-project-info/releases/tag/v3.0.1
> bump: api-doc 1.1.0; lb-project-info 3.0.1
